- name: install dependencies
  ansible.builtin.command: pnpm install:server
  args:
    chdir: /home/{{ USERNAME }}/chessu/
  become: true

- name: Create .env file
  ansible.builtin.template:
    src: .env.j2
    dest: /home/{{USERNAME}}/chessu/server/.env
    owner: "{{ USERNAME }}"
    group: "{{ USERNAME }}"
    mode: '0644'
  become: true

- name: Build server
  ansible.builtin.command: pnpm build:server
  args:
    chdir: /home/{{ USERNAME }}/chessu/
  become: true

- name: Start backend with PM2
  ansible.builtin.command: pm2 start --name server "pnpm start"
  args:
    chdir: /home/{{ USERNAME }}/chessu/server
  become: true

- name: Save PM2 process list
  ansible.builtin.command: pm2 save
  become: true

- name: Setup PM2 to launch on startup
  ansible.builtin.command: pm2 startup systemd -u {{ USERNAME }} --hp /home/{{ USERNAME }}
  become: true
