- name: install dependencies
  ansible.builtin.command: pnpm install:server
  args:
    chdir: /home/{{ USERNAME }}/chessu/
  become: true

- name: Create .env file
  ansible.builtin.template:
    src: .env.j2
    dest: /home/{{USERNAME}}/chessu/server/.env
    owner: "{{ USERNAME }}"
    group: "{{ USERNAME }}"
    mode: '0644'
  become: true

- import_tasks: setup.yml