- name: Configure OpenTelemetry Collector
  ansible.builtin.template:
    src: server-otel-config.yaml.j2
    dest: "{{ splunk_collector_config_path }}"
  become: true
  notify: Restart otel collector