- name: Build server
  ansible.builtin.command: pnpm build:server
  args:
    chdir: /home/{{ USERNAME }}/chessu/
  become: true

- name: Start client with PM2
  ansible.builtin.command: pm2 start --name server "pnpm start"
  args:
    chdir: /home/{{ USERNAME }}/chessu/server
  become: true

- name: Save PM2 process list
  ansible.builtin.command: pm2 save
  become: true