- name: Build client
  ansible.builtin.command: pnpm build:client
  args:
    chdir: /home/{{ USERNAME }}/chessu/
  become: true

- name: Start client with PM2
  ansible.builtin.command: pm2 start --name client "pnpm start"
  args:
    chdir: /home/{{ USERNAME }}/chessu/client
  become: true

- name: Save PM2 process list
  ansible.builtin.command: pm2 save
  become: true