FROM node:lts-alpine3.20

ENV PNPM_HOME=/usr/local/bin \
    NODE_ENV=production

WORKDIR /opt/chessu/

COPY \
  pnpm-workspace.yaml \
  pnpm-lock.yaml \
  server/package.json \
  types/ \
  ./

COPY ./server/ ./server/
COPY server/instrumentation.js ./server/instrumentation.js
COPY ./db_cert.pem /var/db_cert.pem

RUN apk update && \
    corepack enable && corepack prepare pnpm@latest --activate && \
    pnpm config set store-dir /opt/chessu/.pnpm-store && \
    pnpm install --filter server --unsafe-perm && \
    pnpm add --filter server  @opentelemetry/auto-instrumentations-node \
    @opentelemetry/sdk-node \
    @opentelemetry/exporter-trace-otlp-proto \
    @opentelemetry/exporter-metrics-otlp-proto \
    @opentelemetry/instrumentation \
    @opentelemetry/sdk-metrics && \
    pnpm --filter server build
ENV NODE_OPTIONS="--require /opt/chessu/server/instrumentation.js"
CMD ["pnpm", "--filter", "server", "start"]
