# ---------- BUILD STAGE ----------
FROM node:lts-alpine3.20 AS builder

ARG NEXT_PUBLIC_API_URL
ENV PNPM_HOME=/usr/local/bin \
    NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL

WORKDIR /chessu
COPY . .

RUN apk add --no-cache libc6-compat && \
    corepack enable && corepack prepare pnpm@latest --activate && \
    pnpm install --frozen-lockfile && \
    pnpm --filter client build

# ---------- RUN STAGE ----------
FROM node:lts-alpine3.20 AS runner

ENV NODE_ENV=production
WORKDIR /chessu

COPY --from=builder /chessu/client/.next/standalone ./
COPY --from=builder /chessu/client/.next/static ./client/.next/static
COPY --from=builder /chessu/client/public ./client/public

EXPOSE 3000
CMD ["node", "client/server.js"]
