
services:
  chessu_client:
    build:
      context: .
      dockerfile: Dockerfile_client
      args:
        - NEXT_PUBLIC_API_URL=http://192.168.0.222
    expose:
      - "3000"
    labels:
      - nginx.group=client
      - nginx.port=3000
    networks:
      - chessu_network
  chessu_server:
    build:
      context: .
      dockerfile: Dockerfile_server
    expose:
      - "3001"
    depends_on:
      - db
    environment:
      - CORS_ORIGIN=http://192.168.0.222
    labels:
      - nginx.group=server
      - nginx.port=3001
    env_file:
      - ./docker/env/server.env
    networks:
      - chessu_network
  db:
    image: postgres:15
    container_name: db
    env_file: ./docker/env/db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chessu_network
  nginx:
    image: nginx:alpine-otel
    container_name: nginx
    expose:
      - "10080"
    ports:
      - "80:80"
    depends_on:
      - chessu_client
      - chessu_server
      - docker-gen
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./docker/nginx/opentelemetry_module.conf:/etc/nginx/conf.d/opentelemetry_module.conf
    networks:
      - chessu_network
  docker-gen:
    image: nginxproxy/docker-gen
    container_name: nginx-proxy-gen
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/default.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - chessu_network
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    user: "0"
    expose:
      - "4317"
    env_file:
      - ./docker/env/otelcol.env
    volumes:
      - ./docker/otel/otel-config.yml:/etc/otel/config.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["--config", "/etc/otel/config.yml"]
    networks:
      - chessu_network
  splunk:
    image: splunk/splunk:latest
    container_name: splunk
    env_file:
      - ./docker/env/splunk.env
    expose:
      - 8088
    ports:
      - "8000:8000"
    volumes:
      - splunk_var:/opt/splunk/var
      - splunk_etc:/opt/splunk/etc
    networks:
      - chessu_network
      
volumes:
  postgres_data:
  splunk_var:
  splunk_etc:

networks:
  chessu_network:
    driver: bridge
