- import_tasks: install.yml
- import_tasks: configure.yml
- import_tasks: setup.yml

- name: Set password for postgres superuser
  community.postgresql.postgresql_user:
    name: postgres
    password: "{{ db_superuser_password }}"
    encrypted: true
    role_attr_flags: SUPERUSER
  become: true
  become_user: postgres

- include_tasks: otel.yml