- name: Create PostgreSQL user
  community.postgresql.postgresql_user:
    name: "{{ pguser }}"
    password: "{{ pgpassword }}"
    encrypted: yes
    role_attr_flags: LOGIN
  become_user: postgres

- name: Create PostgreSQL database
  community.postgresql.postgresql_db:
    name: chessu
    encoding: UTF8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0
    owner: "{{ pguser }}"
  become_user: postgres

- name: Grant all privileges on database to user
  community.postgresql.postgresql_privs:
    database: "{{ pgname }}"
    role: "{{ pguser }}"
    privs: ALL
    type: database
  become_user: postgres