- name: Generate SHA-512 hashed password
  ansible.builtin.set_fact:
    hashed_password: "{{ PASSWORD | password_hash('sha512') }}"

- name: Create common application user
  ansible.builtin.user:
    name: "{{ USERNAME }}"
    password: "{{ hashed_password }}"
    shell: /bin/bash
    groups: sudo
    append: yes
    create_home: yes
  become: true