- name: Download otel collector
  ansible.builtin.get_url:
    url: "https://github.com/signalfx/splunk-otel-collector/releases/download/v0.126.0/splunk-otel-collector_0.126.0_amd64.deb"
    dest: /tmp/splunk-otel-collector_0.126.0_amd64.deb
  become: true

- name: Install otel collector
  ansible.builtin.apt:
    deb: /tmp/splunk-otel-collector_0.126.0_amd64.deb
  become: true

- name: Configure otel collector
  ansible.builtin.template:
    src: splunk-otel-collector.conf.j2
    dest: /etc/otel/collector/splunk-otel-collector.conf
  become: true