receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
      disk:
      filesystem:
      memory:
      network:
      load:
      paging:
      processes:
processors:
  batch:
    send_batch_size: 1000
    timeout: 10s
    metadata_keys:
      - X-SF-Token
  resourcedetection:
    detectors: [gcp, ecs, ec2, azure, system]
    override: true

exporters:
  # debug:
  #   verbosity: detailed

  sapm:
    access_token: "${SPLUNK_ACCESS_TOKEN}"
    endpoint: https://ingest.eu1.signalfx.com/v2/trace

  signalfx:
    access_token: "${SPLUNK_ACCESS_TOKEN}"
    api_url: https://api.eu1.signalfx.com
    ingest_url: https://ingest.eu1.signalfx.com
    sync_host_metadata: true
    correlation:
    
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [sapm]

    metrics:
      receivers: [otlp, hostmetrics]
      processors: [resourcedetection, batch]
      exporters: [signalfx]
