#!/bin/bash

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $APP_USER WITH PASSWORD '$APP_PASS';
    CREATE USER $OTEL_USER WITH PASSWORD '$OTEL_PASS';

    CREATE DATABASE $APP_DB OWNER $APP_USER;

    GRANT ALL PRIVILEGES ON DATABASE $APP_DB TO $APP_USER;
    GRANT pg_monitor TO $OTEL_USER;
EOSQL
