env:                                      # The environment, mandatory
  contexts:                               # List of 1 or more contexts, mandatory
    - name: context 1                     # Name to be used to refer to this context in other jobs, mandatory
      urls: 
        - http://nginx         # The top level url, mandatory, everything under this will be included
  parameters:
    failOnError: true                  # If set exit on an error
    failOnWarning: false               # If set exit on a warning
    progressToStdout: true             # If set will write job progress to stdout

jobs:
  - type: spider                       # The traditional spider - fast but doesnt handle modern apps so well
    parameters:
      context: context 1
      maxDepth: 3
      parseSitemapXml: true
      handleParameters: use_all
      acceptCookies: true
      threadCount: 3
  - type: passiveScan-wait             # Passive scan wait for the passive scanner to finish
    parameters:
      maxDuration: 1                   # Int: The max time to wait for the passive scanner, default: 0 unlimited
  - type: activeScan                   # The active scanner - this actively attacks the target so should only be used with permission
    parameters:
      context: context 1                        # String: Name of the context to attack, default: first context
    policyDefinition:                  # The policy definition - only used if the 'policy' is not set
      defaultStrength: Low    # String: The default Attack Strength for all rules, one of Low, Medium, High, Insane (not recommended), default: Medium
      defaultThreshold: Off  # String: The default Alert Threshold for all rules, one of Off, Low, Medium, High, default: Medium
      rules:
        - id: 40012   # Cross Site Scripting (Reflected)
          threshold: Medium
          strength: Medium
        - id: 40018   # SQL Injection
          threshold: Medium
          strength: Medium
        - id: 40034   # Path Traversal
          threshold: Medium
          strength: Medium
        - id: 90020   # Cross Site Scripting (Persistent)
          threshold: Medium
          strength: Medium
        - id: 90021   # SQL Injection (Hypothetical)
          threshold: Medium
          strength: Medium
        - id: 90023   # Remote File Inclusion
          threshold: Medium
          strength: Medium

  - type: report                       # Report generation
    parameters:                   
      reportDir: /tmp/zap/    # String: The directory into which the report will be written     