- name: Ensure required shared libraries for otel module are installed
  ansible.builtin.apt:
    name: libprotobuf23
    state: present
  become: true

- name: Install nginx_otel_module
  ansible.builtin.apt:
    name: nginx-module-otel
    state: present
  become: true

- name: Create otel module config
  ansible.builtin.template:
    src: module_config.conf.j2
    dest: "/etc/nginx/conf.d/otel_module.conf"
  become: true

- name: Ensure OpenTelemetry module is loaded in nginx.conf
  ansible.builtin.lineinfile:
    path: /etc/nginx/nginx.conf
    line: "load_module modules/ngx_otel_module.so;"
    insertbefore: BOF
    state: present
  become: true
  notify: Restart nginx

- name: Configure OpenTelemetry Collector
  ansible.builtin.template:
    src: nginx-otel-config.yaml.j2
    dest: "{{ splunk_collector_config_path }}"
  become: true
  notify: Restart otel collector