- hosts: all
  become: no
  tasks:
    - name: set app directory
      ansible.builtin.shell: /vagrant/scripts/set_app_directory.sh

    - name: install nodejs
      ansible.builtin.shell: /vagrant/scripts/install_nodejs.sh

    - name: install pnpm
      ansible.builtin.shell: sudo npm install -g pnpm
      args:
        executable: /bin/bash

    - name: install dependencies
      ansible.builtin.shell:  pnpm install
      args:
        chdir: ~/chessu
        executable: /bin/bash

    - name: install pm2
      ansible.builtin.shell: sudo npm install pm2@latest -g
      args:
        executable: /bin/bash
    
    - name: start app
      ansible.builtin.shell: pm2 start --name {{ name }} "pnpm dev:{{ name }}"
      args:
        chdir: ~/chessu
        executable: /bin/bash