---
- hosts: db
  become: yes
  vars:
    db_user: user
    db_name: chessu

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install PostgreSQL
      ansible.builtin.apt:
        name: postgresql
        state: present

    - name: Ensure PostgreSQL is listening on all interfaces
      ansible.builtin.lineinfile:
        path: /etc/postgresql/14/main/postgresql.conf
        regexp: '^#?listen_addresses'
        line: "listen_addresses = '*'"

    - name: Allow external connections to PostgreSQL
      ansible.builtin.lineinfile:
        path: /etc/postgresql/14/main/pg_hba.conf
        line: "host    {{ db_name }}    {{ db_user }}    192.168.50.0/24    md5"
        insertafter: EOF

    - name: Restart PostgreSQL
      ansible.builtin.systemd:
        name: postgresql
        state: restarted
        enabled: yes