- hosts: all
  become: no
  vars:
    node_bin: "{{ ansible_env.HOME }}/.nvm/versions/node/v22.15.0/bin"
    pnpm_home: "{{ ansible_env.HOME }}/.local/share/pnpm"
    full_path: "{{ pnpm_home }}:{{ node_bin }}:{{ ansible_env.PATH }}"
  tasks:
    - name: install nodejs
      ansible.builtin.shell: /vagrant/scripts/install_nodejs.sh

    - name: set app directory
      ansible.builtin.shell: /vagrant/scripts/set_app_directory.sh

    - name: install pnpm
      ansible.builtin.shell: /vagrant/scripts/install_pnpm.sh
      environment:
        PATH: "{{ full_path }}"

    - name: install dependencies
      ansible.builtin.shell: /vagrant/scripts/install_dependencies.sh
      environment:
        PATH: "{{ full_path }}"