receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
      memory:
      network:
      disk:
      filesystem:
      load:
      paging:
      processes:
  filelog:
    include: [ /tmp/app.log ]
    start_at: beginning
    operators:
      - type: regex_parser
        regex: '^(?P<message>.*)$'
        parse_to: body

processors:
  batch:
    send_batch_size: 1000
    timeout: 10s
    metadata_keys:
      - X-SF-Token
  resourcedetection:
    detectors: [gcp, ecs, ec2, azure, system]
    override: true
    

exporters:
  # debug:
  #   verbosity: detailed

  sapm:
    access_token: "${SPLUNK_ACCESS_TOKEN}"
    endpoint: https://ingest.eu1.signalfx.com/v2/trace

  signalfx:
    access_token: "${SPLUNK_ACCESS_TOKEN}"
    api_url: https://api.eu1.signalfx.com
    ingest_url: https://ingest.eu1.signalfx.com
    sync_host_metadata: true
    correlation:

  splunk_hec:
    token: "${SPLUNK_HEC_TOKEN}"
    endpoint: "https://prd-p-ahb3m.splunkcloud.com:8088"
    source: "client"
    sourcetype: "_json"
    tls:
      insecure_skip_verify: true
      
service:
  pipelines:
    logs:
      receivers: [filelog]
      processors: [resourcedetection, batch]
      exporters: [splunk_hec]

    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [sapm]

    metrics:
      receivers: [otlp, hostmetrics]
      processors: [resourcedetection, batch]
      exporters: [signalfx]
