receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
      memory:
      network:
      disk:
      filesystem:
      load:
      paging:
      processes:

processors:
  batch:

exporters:
  debug:
    verbosity: detailed

  otlphttp/splunk:
    endpoint: https://ingest.eu1.signalfx.com/v2/otlp
    headers:
      "X-SF-TOKEN": "${SPLUNK_ACCESS_TOKEN}"

  signalfx:
    access_token: "${SPLUNK_ACCESS_TOKEN}"
    realm: "eu1"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, signalfx]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlphttp/splunk]

    metrics:
      receivers: [otlp, hostmetrics]
      processors: [batch]
      exporters: [debug, signalfx]
